# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  webRepository: 'mywebapp'
  RegistryName: 'arunsidnal'
  WebAppName: 'arunsMyWebApp'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:    
    - task: Docker@2
      inputs:
        containerRegistry: 'NewDockerConnection'
        repository: 'arunsidnal/mywebapp'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(Build.BuildId)'
 
    - task: Docker@2
      inputs:
        containerRegistry: 'NewDockerConnection'
        repository: 'arunsidnal/mywebapp'
        command: 'Push'
        tags: '$(Build.BuildId)'
- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'
    
    steps:
    - task: AzureWebAppContainer@1
      inputs:
       appName: $(WebAppName)
       azureSubscription: 'Free Trial (413ebf87-ac1e-423e-9fce-f78084d4c2d1)'
       imageName: $(RegistryName)/$(webRepository):$(build.buildId)